name: Render documents with rmarkdown-action
on: [push]
jobs:
  render:
    name: Render my tutorials
    runs-on: ubuntu-latest
    env:
      GH_PAT : ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-pandoc@v1
      
      - uses: r-lib/actions/setup-tinytex@v1
      
      - name: install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
        
      - name: Render document
        run: Rscript ./doc/render.R
        
      - name: Commit result
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -am "rebuild" || echo "No changes to commit"
          git push origin || echo "No change to push !"
